spring:
  application:
    name: order-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: username        # H2 DB ?? ID (??? ??)
    password: password        # H2 DB ?? PW (??? ??)

    # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??
  data:
    jdbc:
      dialect: h2

logging:
  level:
    "org.springframework": DEBUG
    "org.hibernate.orm.jdbc.bind": DEBUG
